### ISSUE TITLE
RFE: Support for setting seuser in selinux_fcontexts

### ISSUE THREAD

**Issue by benblasco** [linux-system-roles/selinux#106]
I see a comment in https://github.com/linux-system-roles/selinux/blob/master/tasks/main.yml suggesting that seuser and selevel handling functionality need to be added to this role:
```
    # FIXME: selevel, seuser
```

The community sefcontext module handles this by not touching the seuser if none is defined:
https://github.com/ansible-collections/community.general/blob/main/plugins/modules/system/sefcontext.py
```
     if seuser is None:
                seuser = orig_seuser
```
Is it straightforward enough to add a conditional to this role to not attempt to pass seuser (or selevel) to the sefcontext if the value is not defined?  I would be happy to contribute a PR for this functionality if this is what we envisage that the role needs.

**Comment by richm** [comment]
Will this fix the issue?
```yaml
- name: Set SELinux file contexts
  sefcontext:
    target: "{{ item.target }}"
    setype: "{{ item.setype }}"
    ftype: "{{ item.ftype | default('a') }}"
    state: "{{ item.state | default('present') }}"
    selevel: "{{ item.selevel | default(omit) }}"
    seuser: "{{ item.seuser | default(omit) }}"
  with_items: "{{ selinux_fcontexts }}"
```
That is - if selevel is not present in item, do not pass it to the sefcontext module.
