### ISSUE TITLE
SELinux mode is not set on RHEL9 if SELinux is disabled

### ISSUE THREAD

**Issue by aklyachkin** [linux-system-roles/selinux#274]
The playbook from Red Hat Training:

```yaml
---
- name: Enable SELinux
  hosts: all
  vars:
    selinux_state: enforcing
    selinux_policy: targeted

  tasks:
    - name: Apply SELinux role
       block:
         - name: Apply the role
            include_role:
              name: redhat.rhel_system_roles.selinux
      
       rescue:
         - name: Check for failure for other reasons than required reboot
            ansible.builtin.fail:
            when: not selinux_reboot_required

         - name: Restart managed host
            ansible.builtin.reboot:

         - name: Reapply SELinux role to complete changes
            ansible.builtin.include_role:
               name: redhat.rhel_system_roles.selinux
```

If the server has SELinux disabled, the playbook fails with an error, and SELinux mode is not set.
The problem is that the role doesn't update GRUB parameters. In RHEL9 this is required and the kernel param must be changed to disable or to enable SELinux.
The ansible.posix.selinux has special option - update_kernel_param. The role doesn't use it.
In tasks/main.yml, lines 14-20 should look like:

```
- name: Set permanent SELinux state if disabled
  # noqa args[module] fqcn[action]
  selinux:
    state: "{{ selinux_state }}"
    policy: "{{ selinux_policy | default('targeted', true) }}"
    update_kernel_param: true
  register: selinux_mod_output_disabled
  when: ansible_selinux.status == "disabled" and selinux_state
```
